const projects = [
  {
    title: "Judiciary of Kenya Supplier Portal",
    description:
      "A production e-procurement platform that enables suppliers to discover tenders, submit bids, upload documents, provide financial responses, manage tender security, and track procurement activities.",
    tech: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "Tailwind CSS",
      "ASP.NET Core",
      "C#",
      "REST API",
      
      "OData",
      "SOAP",
    ],
    github: "",
    live: "https://supplier.judiciary.go.ke/",
    featured: true,
    image: "/projects/supplier-portal.png",
  },
  {
    title: "Judiciary of Kenya Contractors Portal",
    description:
      "A contract management platform for approved contractors and suppliers to manage active contracts, payment requests, instructions, amendments, extensions, approvals, practical completion, and defect workflows.",
    tech: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "ASP.NET Core",
      "C#",
      "REST API",
      "SQL Server",
      
      "OData",
      "SOAP",
    ],
    github: "",
    live: "https://contractors.judiciary.go.ke/",
    featured: true,
    image: "/projects/contractor-portal.png",
  },
  {
    title: "NUPEA Supplier Portal",
    description:
      "A supplier management and procurement portal supporting supplier registration, profile management, document submission, procurement opportunities, and enterprise system integration.",
    tech: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Tailwind CSS",
      "ASP.NET Core",
      "C#",
      "REST API",
      
      "OData",
      "SOAP",
    ],
    github: "",
    live: "https://suppliers.nuclear.co.ke:8086/",
    featured: true,
    image: "",
  },
  {
    title: "PPRA E-Recruitment Portal",
    description:
      "A responsive recruitment platform for publishing vacancies and managing candidate applications, including job search, filtering, pagination, validation, and applicant workflows.",
    tech: [
      "React",
      "TypeScript",
      "Redux Toolkit",
      "Tailwind CSS",
      "ASP.NET Core",
      "REST API",
      "SQL Server",
    ],
    github: "",
    live: "https://erp.ppra.go.ke/",
    featured: true,
    image: "/projects/ppra-recruitment.png",
  },
  {
    title: "DevPulse",
    description:
      "An AI-powered developer community platform for publishing articles, discussions, comments, search, media management, and intelligent content creation.",
    tech: [
      "React",
      "TypeScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Clerk",
      "OpenAI API",
      "Cloudinary",
      "Docker",
      "Google Cloud Build",
    ],
    github: "",
    live: "https://devpulse.blog/",
    featured: true,
    image: "/projects/devpulse.png",
  },
  {
    title: "AI-Powered OData MVC Code Generator",
    description:
      "An AI-powered development tool that generates ASP.NET MVC, API, frontend, and backend code from Microsoft Dynamics 365 Business Central OData schemas, reducing repetitive development work by approximately 85%.",
    tech: [
      "React",
      "TypeScript",
      "Node.js",
      "OpenAI API",
      "OData",   
      "ASP.NET MVC",
      "C#",
    ],
    github: "",
    live: "https://mvcgenerator.vercel.app/",
    featured: true,
    image: "/projects/mvc-generator.png",
  },
  {
    title: "Employee Self-Service Platform",
    description:
      "An enterprise employee self-service platform supporting leave, claims, imprest, training, payment requests, salary advances, and other internal HR and finance workflows.",
    tech: [
      "React",
      "TypeScript",
      "ASP.NET Core",
      "C#",
      "SQL Server",
      "REST API",     
      "OData",
      "SOAP",
      "M-Pesa Daraja API",
    ],
    github: "",
    live: "",
    featured: false,
    image: "",
  },
  {
    title: "M-Pesa Salary Advance Integration",
    description:
      "An M-Pesa Daraja API integration for processing employee salary advance and emergency loan disbursements with transaction validation, callbacks, status tracking, and error handling.",
    tech: [
      "ASP.NET Core",
      "C#",
      "M-Pesa Daraja API",
      "REST API",
      "Webhooks",
      "SQL Server",
      "React",
    ],
    github: "",
    live: "",
    featured: false,
    image: "",
  },
  {
    title: "AudiSpot254",
    description:
      "An e-commerce and automotive platform for browsing Audi vehicle parts, accessories, merchandise, and blog content with integrated digital payment workflows.",
    tech: [
      "React",
      "JavaScript",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Paystack",
      "REST API",
    ],
    github: "",
    live: "",
    featured: false,
    image: "",
  },
  {
    title: "React Spotlight Search",
    description:
      "A reusable React package for implementing fast and customizable spotlight-style search experiences in web applications.",
    tech: ["React", "TypeScript", "NPM", "JavaScript"],
    github: "",
    live: "https://www.npmjs.com/package/@nobertdev/react-spotlight-search",
    featured: false,
    image: "/projects/react-spotlight-search.png",
  },
  {
    title: "React Confirm Dialog",
    description:
      "A reusable and customizable React confirmation dialog package designed for confirmation workflows and destructive user actions.",
    tech: ["React", "TypeScript", "NPM", "JavaScript"],
    github: "",
    live: "https://www.npmjs.com/package/@nobertdev/react-confirm-dialog",
    featured: false,
    image: "/projects/react-confirm-dialog.png",
  },
  {
    title: "React 3D Icons",
    description:
      "A reusable React component library providing 3D-style icons for modern web interfaces and interactive applications.",
    tech: ["React", "TypeScript", "NPM", "JavaScript"],
    github: "",
    live: "https://www.npmjs.com/package/@nobertdev/react-3d-icons",
    featured: false,
    image: "/projects/react-3d-icons.png",
  },
  {
    title: "Portfolio",
    description:
      "This portfolio — built with Next.js, Tailwind CSS, and Framer Motion. Features a dark-themed design system, smooth scroll animations, a categorized skills grid, and a timeline-based experience section.",
    tech: ["TypeScript", "Next.js", "Tailwind CSS", "Framer Motion"],
    github: "https://github.com/NOBERT167/my-portfolio",
    live: "https://nobertdev.vercel.app",
    featured: true,
    image: "",
  },
  {
    title: "EazySell",
    description:
      "Full-stack e-commerce platform for listing, browsing, and managing products. Built on the MERN stack with JWT authentication, product CRUD, and a responsive storefront.",
    tech: ["JavaScript", "MongoDB", "Express", "React", "Node.js"],
    github: "https://github.com/NOBERT167/EazySell",
    featured: true,
  },
  {
    title: "ShopYangu",
    description:
      "Shop and product management app with full CRUD, search, and shop-to-product association. Built with Next.js and React as a frontend-focused project.",
    tech: ["TypeScript", "Next.js", "React"],
    github: "https://github.com/NOBERT167/ShopYangu",
    image: "/projects/shop-yangu.png",
    live: "https://shop-yangu-phi.vercel.app",
    featured: false,
  },
  {
    title: "Fitness Zone",
    description:
      "A modern gym website landinga page with a sleek UI, modern UI/UX, animations and responsive design.",
    tech: ["React", "Framer Motion", "styled-components"],
    github: "https://github.com/NOBERT167/gym-website",
    live: "https://fitness-zone.netlify.app/",
    image: "/projects/fitness-zone.png",
    featured: false,
  },
  {
    title: "Afrinova",
    description:
      "Web project celebrating African innovation, built with clean HTML and CSS. Focuses on typography, layout, and visual storytelling.",
    tech: ["HTML", "CSS", "JavaScript"],
    github: "",
    live: "https://nobert167.github.io/Afrinova",
    image: "/projects/afrinova.png",
    featured: false,
  },
];

export default projects;
